version: "3"

tasks:
  build:
    cmds:
      - go build -v -o build/main main.go
      - go build -buildmode=plugin -o build/days/day1.so days/day1.go

  run:
    cmds:
      - ./build/main {{.CLI_ARGS}}
