version: "3"

tasks:
  build:
    vars:
      DAYS:
        sh: find days -name 'day*.go'
    cmds:
      - go build -v -o build/main main.go
      - for: { var: DAYS }
        cmd: go build -buildmode=plugin -o build/{{.ITEM}}.so {{.ITEM}}

  run:
    cmds:
      - ./build/main {{.CLI_ARGS}}
